#!/usr/bin/env python3
"""Create balanced per-GPU configs for short/full-JSON edit TE caching."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


DATASET_ROOT = Path("/mnt/images/a.gainetdionov/Datasets/es_hunt_only")
DEFAULT_EXP_DIR = Path("_train/exp/sft_lork_lr_3e-4_1328_640_img_1_0")
DEFAULT_NFS_ROOT = Path(
    "/mnt/images-not-ha/a.gainetdinov/qwen_sft_cache/"
    "sft_lork_lr_3e-4_1328_640_img_1_0"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare Qwen-Image edit TE cache shards.")
    parser.add_argument(
        "--short-jsonl",
        type=Path,
        default=DATASET_ROOT / "es_hunt_real_edit_short.jsonl",
    )
    parser.add_argument(
        "--full-jsonl",
        type=Path,
        default=DATASET_ROOT / "es_hunt_real_edit_json.jsonl",
    )
    parser.add_argument(
        "--shard-dir",
        type=Path,
        default=DATASET_ROOT / "sft_real_edit_cache_shards",
    )
    parser.add_argument(
        "--config-dir",
        type=Path,
        default=DEFAULT_EXP_DIR / "te_cache_configs",
    )
    parser.add_argument("--cache-root", type=Path, default=DEFAULT_NFS_ROOT / "te_shards")
    parser.add_argument("--num-shards", type=int, default=8)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def write_atomic(path: Path, content: str, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} exists; pass --overwrite to replace it")
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(f".{path.name}.tmp")
    temp.write_text(content, encoding="utf-8")
    os.replace(temp, path)


def record_identity(line: str, source: Path, line_number: int) -> tuple[str, str]:
    try:
        record = json.loads(line)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSONL at {source}:{line_number}: {exc}") from exc
    image_path = record.get("image_path")
    control_path = record.get("control_path")
    if not isinstance(image_path, str) or not isinstance(control_path, str):
        raise ValueError(f"Missing image/control path at {source}:{line_number}")
    return image_path, control_path


def make_config(
    short_jsonl: Path,
    full_jsonl: Path,
    short_cache: Path,
    full_cache: Path,
) -> str:
    return f"""# Auto-generated by _train/scripts/prepare_te_cache_shards.py
# Qwen-Image-Edit TE depends on caption + control image, not target resolution.
[general]
enable_bucket = true
bucket_no_upscale = true
batch_size = 1

[[datasets]]
image_jsonl_file = "{short_jsonl.resolve()}"
cache_directory = "{short_cache.resolve()}"
resolution = [1328, 1328]
num_repeats = 1
control_resolution = [1024, 1024]
no_resize_control = false

[[datasets]]
image_jsonl_file = "{full_jsonl.resolve()}"
cache_directory = "{full_cache.resolve()}"
resolution = [1328, 1328]
num_repeats = 1
control_resolution = [1024, 1024]
no_resize_control = false
"""


def main() -> None:
    args = parse_args()
    if args.num_shards < 1:
        raise ValueError("--num-shards must be >= 1")

    with args.short_jsonl.open(encoding="utf-8") as source:
        short_lines = source.readlines()
    with args.full_jsonl.open(encoding="utf-8") as source:
        full_lines = source.readlines()
    if len(short_lines) != len(full_lines) or not short_lines:
        raise ValueError(
            f"Manifest size mismatch: short={len(short_lines)}, full={len(full_lines)}"
        )

    for index, (short_line, full_line) in enumerate(zip(short_lines, full_lines), start=1):
        short_identity = record_identity(short_line, args.short_jsonl, index)
        full_identity = record_identity(full_line, args.full_jsonl, index)
        if short_identity != full_identity:
            raise ValueError(
                f"Short/full manifest identity mismatch at line {index}: "
                f"{short_identity} != {full_identity}"
            )

    quotient, remainder = divmod(len(short_lines), args.num_shards)
    offset = 0
    counts: list[int] = []

    for shard_idx in range(args.num_shards):
        count = quotient + (1 if shard_idx < remainder else 0)
        shard_short_lines = short_lines[offset : offset + count]
        shard_full_lines = full_lines[offset : offset + count]
        offset += count

        short_shard = args.shard_dir / f"te_short_{shard_idx:02d}.jsonl"
        full_shard = args.shard_dir / f"te_json_{shard_idx:02d}.jsonl"
        short_cache = args.cache_root / f"shard_{shard_idx:02d}" / "short"
        full_cache = args.cache_root / f"shard_{shard_idx:02d}" / "json"
        short_cache.mkdir(parents=True, exist_ok=True)
        full_cache.mkdir(parents=True, exist_ok=True)

        write_atomic(short_shard, "".join(shard_short_lines), args.overwrite)
        write_atomic(full_shard, "".join(shard_full_lines), args.overwrite)
        config_path = args.config_dir / f"te_{shard_idx:02d}.toml"
        write_atomic(
            config_path,
            make_config(short_shard, full_shard, short_cache, full_cache),
            args.overwrite,
        )
        counts.append(count)
        print(f"shard {shard_idx:02d}: short={count}, full={count}, config={config_path}")

    assert offset == len(short_lines)
    print(
        f"Prepared {args.num_shards} paired TE shards: "
        f"per variant total={sum(counts)}, min={min(counts)}, max={max(counts)}"
    )


if __name__ == "__main__":
    main()
