#!/usr/bin/env python3
"""Split the real-only edit manifest and create per-GPU latent-cache configs."""

from __future__ import annotations

import argparse
import os
from pathlib import Path


DATASET_ROOT = Path("/mnt/images/a.gainetdionov/Datasets/es_hunt_only")
DEFAULT_EXP_DIR = Path("_train/exp/sft_lork_lr_3e-4_1328_640_img_1_0")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare balanced Qwen-Image latent-cache shards.")
    parser.add_argument(
        "--input-jsonl",
        type=Path,
        default=DATASET_ROOT / "es_hunt_real_edit_short.jsonl",
    )
    parser.add_argument(
        "--shard-dir",
        type=Path,
        default=DATASET_ROOT / "sft_real_edit_cache_shards",
    )
    parser.add_argument(
        "--config-dir",
        type=Path,
        default=DEFAULT_EXP_DIR / "latent_cache_configs",
    )
    parser.add_argument(
        "--cache-root",
        type=Path,
        default=DATASET_ROOT,
    )
    parser.add_argument("--num-shards", type=int, default=8)
    parser.add_argument("--batch-size", type=int, default=10)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def write_atomic(path: Path, content: str, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} exists; pass --overwrite to replace it")
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(f".{path.name}.tmp")
    temp.write_text(content, encoding="utf-8")
    os.replace(temp, path)


def make_config(
    shard_jsonl: Path,
    cache_1328: Path,
    cache_640: Path,
    batch_size: int,
) -> str:
    return f"""# Auto-generated by _train/scripts/prepare_latent_cache_shards.py
[general]
enable_bucket = true
bucket_no_upscale = true
batch_size = {batch_size}

[[datasets]]
image_jsonl_file = "{shard_jsonl.resolve()}"
cache_directory = "{cache_1328.resolve()}"
resolution = [1328, 1328]
num_repeats = 1
control_resolution = [1024, 1024]
no_resize_control = false

[[datasets]]
image_jsonl_file = "{shard_jsonl.resolve()}"
cache_directory = "{cache_640.resolve()}"
resolution = [640, 640]
num_repeats = 1
control_resolution = [1024, 1024]
no_resize_control = false
"""


def main() -> None:
    args = parse_args()
    if args.num_shards < 1:
        raise ValueError("--num-shards must be >= 1")
    if args.batch_size < 1:
        raise ValueError("--batch-size must be >= 1")

    with args.input_jsonl.open(encoding="utf-8") as source:
        lines = source.readlines()
    if not lines:
        raise ValueError(f"{args.input_jsonl} is empty")

    quotient, remainder = divmod(len(lines), args.num_shards)
    offset = 0
    counts: list[int] = []

    cache_shards_root = args.cache_root / "cache_qwen_image_sft_real_edit_short_latent_shards"
    for shard_idx in range(args.num_shards):
        count = quotient + (1 if shard_idx < remainder else 0)
        shard_lines = lines[offset : offset + count]
        offset += count

        shard_jsonl = args.shard_dir / f"latent_{shard_idx:02d}.jsonl"
        config_path = args.config_dir / f"latent_{shard_idx:02d}.toml"
        cache_1328 = cache_shards_root / f"shard_{shard_idx:02d}" / "1328"
        cache_640 = cache_shards_root / f"shard_{shard_idx:02d}" / "640"
        cache_1328.mkdir(parents=True, exist_ok=True)
        cache_640.mkdir(parents=True, exist_ok=True)

        write_atomic(shard_jsonl, "".join(shard_lines), args.overwrite)
        write_atomic(
            config_path,
            make_config(shard_jsonl, cache_1328, cache_640, args.batch_size),
            args.overwrite,
        )
        counts.append(count)
        print(f"shard {shard_idx:02d}: {count} rows -> {shard_jsonl}; config={config_path}")

    assert offset == len(lines)
    print(f"Prepared {args.num_shards} shards: total={sum(counts)}, min={min(counts)}, max={max(counts)}")


if __name__ == "__main__":
    main()
